{
 "title": "autoPPP Ginan",
 "time": { "from": "now-16d", "to": "now-2d" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station",
    "query": "SELECT DISTINCT sitename FROM position ORDER BY sitename"
   },
   {
    "name": "solution_count",
    "query": "SELECT COUNT(x) FROM position WHERE sitename = '$station' AND $__timeFilter(time_of_data)"
   }
  ]
 },
 "panels": [
  {
   "title": "$station metadata",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT x, y, z, target_crs_epsg, receiver, antenna, ecc_x, ecc_y, ecc_z, valid_from, valid_to FROM site_metadata WHERE sitename = '$station' AND (\r\n  ($__timeFrom()::date BETWEEN valid_from AND valid_to) OR\r\n  ($__timeFrom()::date >= valid_from AND valid_to IS NULL) OR\r\n  ($__timeTo()::date BETWEEN valid_from AND valid_to) OR\r\n  ($__timeTo()::date >= valid_from AND valid_to IS NULL))"
    }
   ]
  },
  {
   "title": "Statistics for geocentric coordinates based on $solution_count solutions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  coord                         AS \"Coordinate\",\r\n  avg_diff                      As \"Mean difference from reference\",\r\n  avg_val                       AS \"Mean\",\r\n  std_val                       AS \"Standard deviation\"\r\nFROM (\r\n  SELECT 'x' AS coord,\r\n    AVG(p.x)                        AS avg_val,\r\n    AVG(p.x - m.x)                  AS avg_diff,\r\n    STDDEV(p.x)                     AS std_val\r\n  FROM position p\r\n  LEFT OUTER JOIN site_metadata m ON p.sitename = m.sitename\r\n  WHERE p.sitename = '$station' AND $__timeFilter(time_of_data) \r\n\r\n  UNION ALL\r\n\r\n  SELECT 'y',\r\n    AVG(p.y),\r\n    AVG(p.y- m.y),\r\n    STDDEV(p.y)\r\n  FROM position p\r\n  LEFT OUTER JOIN site_metadata m ON p.sitename = m.sitename\r\n  WHERE p.sitename = '$station' AND $__timeFilter(time_of_data) \r\n\r\n  UNION ALL\r\n\r\n  SELECT 'z',\r\n    AVG(p.z),\r\n    AVG(p.z- m.z),\r\n    STDDEV(p.z)\r\n  FROM position p\r\n  LEFT OUTER JOIN site_metadata m ON p.sitename = m.sitename\r\n  WHERE p.sitename = '$station' AND $__timeFilter(time_of_data) \r\n) stats\r\nORDER BY coord ASC;"
    }
   ]
  },
  {
   "title": "Statistics on ENU coordinates based on $solution_count solutions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  coord                         AS \"Coordinate\",\r\n  avg_val                       AS \"Mean\",\r\n  std_val                       AS \"Standard deviation\"\r\nFROM (\r\n  SELECT 'e' AS coord,\r\n    AVG(p.e)                        AS avg_val,\r\n    STDDEV(p.e)                     AS std_val\r\n  FROM position p\r\n  LEFT OUTER JOIN site_metadata m ON p.sitename = m.sitename\r\n  WHERE p.sitename = '$station' AND $__timeFilter(time_of_data) \r\n\r\n  UNION ALL\r\n\r\n  SELECT 'n',\r\n    AVG(p.n),\r\n    STDDEV(p.n)\r\n  FROM position p\r\n  LEFT OUTER JOIN site_metadata m ON p.sitename = m.sitename\r\n  WHERE p.sitename = '$station' AND $__timeFilter(time_of_data) \r\n\r\n  UNION ALL\r\n\r\n  SELECT 'u',\r\n    AVG(p.u),\r\n    STDDEV(p.u)\r\n  FROM position p\r\n  LEFT OUTER JOIN site_metadata m ON p.sitename = m.sitename\r\n  WHERE p.sitename = '$station' AND $__timeFilter(time_of_data) \r\n) stats\r\nORDER BY coord;"
    }
   ]
  },
  {
   "title": "Horizontal difference from reference",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT time_of_data, e as \"East\", n as \"North\" FROM position WHERE $__timeFilter(time_of_data) AND sitename = '$station'"
    }
   ]
  },
  {
   "title": "ENU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT time_of_data as \"time\", e as \"East\", n as \"North\", u as \"Up\" FROM position WHERE $__timeFilter(time_of_data) AND sitename = '$station' "
    }
   ]
  },
  {
   "title": "Height above ellipsoid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  time_of_data AS \"time\",\r\n  h_e as \"Height above ellipsoid\",\r\n  AVG(h_e) OVER (PARTITION BY sitename ORDER BY time_of_data ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) as \"14-day moving average\"\r\n  FROM position WHERE sitename = '$station' AND $__timeFilter(time_of_data) GROUP BY sitename, time_of_data, h_e ORDER BY sitename, time_of_data "
    }
   ]
  },
  {
   "title": "Station Locations",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (sitename) sitename, lat AS latitude, lon AS longitude FROM position WHERE sitename = '$station' ORDER BY sitename, time_of_data DESC"
    }
   ]
  },
  {
   "title": "Latest solutions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT sitename, raw_x, raw_y, raw_z, x, y, z, lat, lon, h_e, time_of_data, time_of_calc FROM position WHERE sitename = '$station' AND $__timeFilter(time_of_data)  ORDER BY sitename, time_of_data DESC"
    }
   ]
  }
 ]
}